common: &common
  adapter: postgresql
  encoding: unicode
  username: postgres

development:
  <<: *common
  database: napolnenie_development

production:
  <<: *common
  database: napolnenie_production

staging:
  <<: *common
  database: napolnenie_staging

test: &test
  <<: *common
  database: napolnenie_test 